Algoritmo "Exercicio15"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Obama
// Data atual  : 15/07/2021
Var
// Seção de Declarações das variáveis
valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um número: ")
Leia(valor)
se(valor>-1)entao
   Escreva("Posiitivo")
senao
   Escreva("Negativo")
fimse
Fimalgoritmo