Algoritmo "Exercicio14"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Obama
// Data atual  : 15/07/2021
Var
// Seção de Declarações das variáveis 
valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite um número: ")
Leia(valor)
se(valor>9)entao
   Escreva("É maior que 10")
senao
   Escreva("É menor que 10")
fimse
Fimalgoritmo